import { Product } from "@/lib/products";

const products: Product[] = [
  {
    slug: "canasto-chico",
    name: "Canasto chico",
    code: "2601/00",
    description: [],
    price: 1795,
    img: "/productos/canasto-chico.jpg",
    tags: ["canastos"],
  },
  {
    slug: "canasto-dos-partes",
    name: "Canasto dos partes",
    code: "2603/00",
    description: [],
    price: 2805,
    img: "/productos/canasto-dos-partes.jpg",
    tags: ["canastos"],
  },
  {
    slug: "caja-organizadora-calada-con-tapa-mediano",
    name: "Caja organizadora calada con tapa mediano",
    code: "2604/00",
    description: [],
    price: 4001,
    img: "/productos/caja-organizadora-calada-con-tapa-mediano.jpg",
    tags: ["canastos"],
  },
  {
    slug: "caja-organizadora-calada-con-tapa-grande",
    name: "Caja organizadora calada con tapa grande",
    code: "2605/00",
    description: [],
    price: 4082.4,
    img: "/productos/caja-organizadora-calada-con-tapa-grande.jpg",
    tags: ["canastos"],
  },
  {
    slug: "cesto-para-ropa",
    name: "Cesto para ropa",
    code: "2606/00",
    description: [],
    price: 4566.8,
    img: "/productos/cesto-para-ropa.jpg",
    tags: ["canastos"],
  },
  {
    slug: "box-rectangular",
    name: "Box rectangular",
    code: "2608/00",
    description: [],
    price: 5194,
    img: "/productos/box-rectangular.jpg",
    tags: ["canastos"],
  },

  {
    slug: "banquito-cuadrado",
    name: "Banquito cuadrado",
    code: "4001/00",
    description: [],
    price: 2587.2,
    img: "/productos/banquito-cuadrado.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banquito-redondo",
    name: "Banquito redondo",
    code: "4002/00",
    description: [],
    price: 2587.2,
    img: "/productos/banquito-redondo.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banquito-oso",
    name: "Banquito oso",
    code: "4003/00",
    description: [],
    price: 2587.2,
    img: "/productos/banquito-oso.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banquito-gato",
    name: "Banquito gato",
    code: "4004/00",
    description: [],
    price: 2587.2,
    img: "/productos/banquito-gato.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banqueta-redonda-negra",
    name: "Banqueta redonda negra",
    code: "4007/00",
    description: [],
    price: 2721.6,
    img: "/productos/banqueta-redonda-negra.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banquito-con-respaldo",
    name: "Banquito con respaldo",
    code: "4008/00",
    description: [],
    price: 5580.4,
    img: "/productos/banquito-con-respaldo.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "sillita-infantil-con-respaldo",
    name: "Sillita infantil con respaldo",
    code: "4009/00",
    description: [],
    price: 2587.2,
    img: "/productos/sillita-infantil-con-respaldo.jpg",
    tags: ["banquetas"],
  },

  {
    slug: "mesa-plastica-infantil",
    name: "Mesa plástica infantil 40x40x40 cm",
    code: "7001/00",
    description: [],
    price: 5863.2,
    img: "/productos/mesa-plastica-infantil.jpg",
    tags: ["mesas"],
  },

  {
    slug: "vaso-stark",
    name: "Vaso Stark",
    code: "5001/00",
    description: [],
    price: 1226.4,
    img: "/productos/vaso-stark.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-con-tapa-grande",
    name: "Vaso con tapa grande",
    code: "5002/01",
    description: [],
    price: 728,
    img: "/productos/vaso-con-tapa-grande.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-largo-con-tapon",
    name: "Vaso largo con tapón",
    code: "5004/00",
    description: [],
    price: 840,
    img: "/productos/vaso-largo-con-tapon.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-grande-con-frase",
    name: "Vaso grande con frase",
    code: "5002/114",
    description: [],
    price: 932.4,
    img: "/productos/vaso-grande-con-frase.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-chico",
    name: "Vaso chico",
    code: "5007/00",
    description: [],
    price: 145,
    img: "/productos/vaso-chico.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-pinguino",
    name: "Vaso pingüino",
    code: "5008/00",
    description: [],
    price: 170,
    img: "/productos/vaso-pinguino.jpg",
    tags: ["vasos"],
  },
  {
    slug: "taza-love",
    name: "Taza love",
    code: "5012/00",
    description: [],
    price: 481.6,
    img: "/productos/taza-love.jpg",
    tags: ["vasos"],
  },
  {
    slug: "taza-trebol",
    name: "Taza trebol",
    code: "5013/00",
    description: [],
    price: 453.6,
    img: "/productos/taza-trebol.jpg",
    tags: ["vasos"],
  },
  {
    slug: "jarro-capuchino",
    name: "Jarro capuchino",
    code: "5014/99",
    description: [],
    price: 481.6,
    img: "/productos/jarro-capuchino.jpg",
    tags: ["vasos"],
  },
  {
    slug: "set-x4-vaso-mug",
    name: "Set x4 vaso mug",
    code: "5015/99",
    description: [],
    price: 1041.6,
    img: "/productos/set-x4-vaso-mug.jpg",
    tags: ["vasos"],
  },
  {
    slug: "set-escolar-triple-formas",
    name: "Set escolar triple formas",
    code: "5017/99",
    description: [],
    price: 1176,
    img: "/productos/set-escolar-triple-formas.jpg",
    tags: ["vasos"],
  },

  {
    slug: "colador-giratorio",
    name: "Colador giratorio",
    code: "9001/00",
    description: [],
    price: 1895.6,
    img: "/productos/colador-giratorio.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "set-jarra-1.7-lts-4-vasos",
    name: "Set jarra 1,7 lts + 4 vasos",
    code: "9002/99",
    description: [],
    price: 1904,
    img: "/productos/set-jarra-1.7-lts-4-vasos.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "organizador-para-heladera",
    name: "Organizador para heladera",
    code: "9003/00",
    description: [],
    price: 1820,
    img: "/productos/organizador-para-heladera.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "escurridor-para-bacha",
    name: "Escurridor para bacha",
    code: "9006/00",
    description: [],
    price: 1988,
    img: "/productos/escurridor-para-bacha.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "big-cupcake",
    name: "Big cupcake",
    code: "9007/00",
    description: [],
    price: 478.8,
    img: "/productos/big-cupcake.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "bowl-postre-sweet",
    name: "Bowl postre sweet",
    code: "9008/00",
    description: [],
    price: 327.6,
    img: "/productos/bowl-postre-sweet.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "bowl-ovalado",
    name: "Bowl ovalado",
    code: "9010/00",
    description: [],
    price: 803.6,
    img: "/productos/bowl-ovalado.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "cazuela",
    name: "Cazuela",
    code: "9011/00",
    description: [],
    price: 560,
    img: "/productos/cazuela.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "cubetera-14",
    name: "Cubetera 14",
    code: "9012/00",
    description: [],
    price: 756,
    img: "/productos/cubetera-14.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "set-cubetera-24-con-tapa",
    name: "Set cubetera 24 con tapa",
    code: "9013/99",
    description: [],
    price: 2380,
    img: "/productos/set-cubetera-24-con-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "dispenser",
    name: "Dispenser",
    code: "9015/00",
    description: [],
    price: 3427.2,
    img: "/productos/dispenser.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "cesto-de-puerta",
    name: "Cesto de puerta",
    code: "9016/00",
    description: [],
    price: 1478.4,
    img: "/productos/cesto-de-puerta.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "plato-infantil-iml",
    name: "Plato infantil IML",
    code: "9017/114",
    description: [],
    price: 582.4,
    img: "/productos/plato-infantil-iml.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "jarra-0.76-lts",
    name: "Jarra 0,76 lts",
    code: "9018/00",
    description: [],
    price: 803.6,
    img: "/productos/jarra-0.76-lts.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "jarra-americana-2.25-lts-con-tapa",
    name: "Jarra americana 2,25 lts con tapa",
    code: "9019/00",
    description: [],
    price: 1453.2,
    img: "/productos/jarra-americana-2.25-lts-con-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "set-jarra-americana-2.25-lts-3-vasos-mug",
    name: "Set jarra americana 2,25 lts + 3 vasos mug",
    code: "9019/99",
    description: [],
    price: 2234.4,
    img: "/productos/set-jarra-americana-2.25-lts-3-vasos-mug.jpg",
    tags: ["artículos de cocina"],
  },

  {
    slug: "balde-10-lts-negro",
    name: "Balde 10 lts negro",
    code: "8001/00",
    description: [],
    price: 1460,
    img: "/productos/balde-10-lts-negro.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "balde-10-lts-eco-color",
    name: "Balde 10 lts eco color",
    code: "8001/99",
    description: [],
    price: 1607.2,
    img: "/productos/balde-10-lts-eco-color.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "jabonera-ballena",
    name: "Jabonera ballena",
    code: "8002/00",
    description: [],
    price: 456.4,
    img: "/productos/jabonera-ballena.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "jabonera-simple",
    name: "Jabonera simple",
    code: "8003/00",
    description: [],
    price: 310.8,
    img: "/productos/jabonera-simple.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "fuenton-oso",
    name: "Fuentón oso",
    code: "8004/00",
    description: [],
    price: 2079,
    img: "/productos/fuenton-oso.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "percha-economica-negro",
    name: "Percha económica negro * 4",
    code: "8006/00",
    description: [],
    price: 582.4,
    img: "/productos/percha-economica-negro.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "percha-economica-color",
    name: "Percha económica color * 4",
    code: "8006/99",
    description: [],
    price: 691.6,
    img: "/productos/percha-economica-color.jpg",
    tags: ["artículos de limpieza"],
  },

  {
    slug: "porta-sube",
    name: "Porta sube",
    code: "PORTFUT 01",
    description: [],
    price: 480,
    img: "/productos/porta-sube.jpg",
    tags: ["varios"],
  },
];

export default products;
