import { Product } from "@/lib/products";

const products: Product[] = [
  {
    slug: "canasto-chico",
    name: "Canasto chico",
    code: "2601/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1795,
    img: "/productos/canasto-chico.jpg",
    tags: ["canastos"],
  },
  {
    slug: "canasto-grande",
    name: "Canasto grande",
    code: "2602/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2493,
    img: "/productos/canasto-grande.jpg",
    tags: ["canastos"],
  },
  {
    slug: "canasto-dos-partes",
    name: "Canasto dos partes",
    code: "2603/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2805,
    img: "/productos/canasto-dos-partes.jpg",
    tags: ["canastos"],
  },
  {
    slug: "caja-organizadora-calada-con-tapa-mediano",
    name: "Caja organizadora calada con tapa mediano",
    code: "2604/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 4001,
    img: "/productos/caja-organizadora-calada-con-tapa-mediano.jpg",
    tags: ["canastos"],
  },
  {
    slug: "caja-organizadora-calada-sin-tapa-mediano",
    name: "Caja organizadora calada sin tapa mediano",
    code: "2604/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 3640,
    img: "/productos/caja-organizadora-calada-sin-tapa-mediano.jpg",
    tags: ["canastos"],
  },
  {
    slug: "caja-organizadora-calada-con-tapa-grande",
    name: "Caja organizadora calada con tapa grande",
    code: "2605/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 4082.4,
    img: "/productos/caja-organizadora-calada-con-tapa-grande.jpg",
    tags: ["canastos"],
  },
  {
    slug: "caja-organizadora-calada-sin-tapa-grande",
    name: "Caja organizadora calada sin tapa grande",
    code: "2605/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 4001.2,
    img: "/productos/caja-organizadora-calada-sin-tapa-grande.jpg",
    tags: ["canastos"],
  },
  {
    slug: "cesto-para-ropa",
    name: "Cesto para ropa",
    code: "2606/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 4566.8,
    img: "/productos/cesto-para-ropa.jpg",
    tags: ["canastos"],
  },
  {
    slug: "box-cuadrado",
    name: "Box cuadrado",
    code: "2607/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 3897.6,
    img: "/productos/box-cuadrado.jpg",
    tags: ["canastos"],
  },
  {
    slug: "box-rectangular",
    name: "Box rectangular",
    code: "2608/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 5194,
    img: "/productos/box-rectangular.jpg",
    tags: ["canastos"],
  },
  {
    slug: "estuche-chico",
    name: "Estuche chico (12,5 * 7 * 2)",
    code: "2609/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 688.8,
    img: "/productos/estuche-chico.jpg",
    tags: ["canastos"],
  },
  {
    slug: "estuche-chico-con-dijes",
    name: "Estuche chico con dijes",
    code: "2609/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2052.4,
    img: "/productos/estuche-chico-con-dijes.jpg",
    tags: ["canastos"],
  },
  {
    slug: "estuche-mediano",
    name: "Estuche mediano (17 * 10 * 2)",
    code: "2610/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 786.8,
    img: "/productos/estuche-mediano.jpg",
    tags: ["canastos"],
  },
  {
    slug: "estuche-mediano-con-dijes",
    name: "Estuche mediano con dijes",
    code: "2610/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2856,
    img: "/productos/estuche-mediano-con-dijes.jpg",
    tags: ["canastos"],
  },

  {
    slug: "banquito-cuadrado",
    name: "Banquito cuadrado",
    code: "4001/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2587.2,
    img: "/productos/banquito-cuadrado.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banquito-redondo",
    name: "Banquito redondo",
    code: "4002/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2587.2,
    img: "/productos/banquito-redondo.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banquito-oso",
    name: "Banquito oso",
    code: "4003/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2587.2,
    img: "/productos/banquito-oso.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banquito-gato",
    name: "Banquito gato",
    code: "4004/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2587.2,
    img: "/productos/banquito-gato.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "taburete-rhino",
    name: "Taburete Rhino",
    code: "4005/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    // Revisar precio
    price: 80442,
    img: "/productos/taburete-rhino.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banqueta-rectangular-negra",
    name: "Banqueta rectangular negra",
    code: "4006/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2290.4,
    img: "/productos/banqueta-rectangular-negra.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banqueta-redonda-negra",
    name: "Banqueta redonda negra",
    code: "4007/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2721.6,
    img: "/productos/banqueta-redonda-negra.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "banquito-con-respaldo",
    name: "Banquito con respaldo",
    code: "4008/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 5580.4,
    img: "/productos/banquito-con-respaldo.jpg",
    tags: ["banquetas"],
  },
  {
    slug: "sillita-infantil-con-respaldo",
    name: "Sillita infantil con respaldo",
    code: "4009/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2587.2,
    img: "/productos/sillita-infantil-con-respaldo.jpg",
    tags: ["banquetas"],
  },

  {
    slug: "mesa-plastica-infantil",
    name: "Mesa plástica infantil 40x40x40 cm",
    code: "7001/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 5863.2,
    img: "/productos/mesa-plastica-infantil.jpg",
    tags: ["mesas"],
  },

  {
    slug: "vaso-stark",
    name: "Vaso Stark",
    code: "5001/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1226.4,
    img: "/productos/vaso-stark.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-stark-con-brillo",
    name: "Vaso Stark con brillo",
    code: "5001/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1386,
    img: "/productos/vaso-stark-con-brillo.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-sorbete-grande",
    name: "Vaso sorbete grande",
    code: "5002/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 728,
    img: "/productos/vaso-sorbete-grande.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-sorbete-mediano",
    name: "Vaso sorbete mediano",
    code: "5003/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 658,
    img: "/productos/vaso-sorbete-mediano.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-con-tapa-grande",
    name: "Vaso con tapa grande",
    code: "5002/01",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 728,
    img: "/productos/vaso-con-tapa-grande.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-con-tapa-mediano",
    name: "Vaso con tapa mediano",
    code: "5003/01",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 658,
    img: "/productos/vaso-con-tapa-mediano.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-decorado",
    name: "Vaso decorado",
    code: "5002/02",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 750,
    img: "/productos/vaso-decorado.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-largo-con-tapon",
    name: "Vaso largo con tapon",
    code: "5004/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 840,
    img: "/productos/vaso-largo-con-tapon.jpg",
    tags: ["vasos"],
  },
  {
    slug: "taza-infantil",
    name: "Taza infantil",
    code: "5005/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1092,
    img: "/productos/taza-infantil.jpg",
    tags: ["vasos"],
  },
  {
    slug: "taza-acrilica-sin-papel",
    name: "Taza acrílica sin papel",
    code: "5005/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 949.2,
    img: "/productos/taza-acrilica-sin-papel.jpg",
    tags: ["vasos"],
  },
  {
    slug: "taza-grande",
    name: "Taza grande",
    code: "5006/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 386.4,
    img: "/productos/taza-grande.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-grande-con-sticker",
    name: "Vaso grande con sticker",
    code: "5002/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1022,
    img: "/productos/vaso-grande-con-sticker.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-grande-con-frase",
    name: "Vaso grande con frase",
    code: "5002/114",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 932.4,
    img: "/productos/vaso-grande-con-frase.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-mediano-con-sticker",
    name: "Vaso mediano con sticker",
    code: "5003/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 980,
    img: "/productos/vaso-mediano-con-sticker.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-mediano-con-frase",
    name: "Vaso mediano con frase",
    code: "5003/114",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 856.8,
    img: "/productos/vaso-mediano-con-frase.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-largo-tapon-con-sticker",
    name: "Vaso largo tapon con sticker",
    code: "5004/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1106,
    img: "/productos/vaso-largo-tapon-con-sticker.jpg",
    tags: ["vasos"],
  },
  {
    slug: "taza-grande-con-sticker",
    name: "Taza grande con sticker",
    code: "5006/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 649.6,
    img: "/productos/taza-grande-con-sticker.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-chico",
    name: "Vaso chico",
    code: "5007/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 145,
    img: "/productos/vaso-chico.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-pinguino",
    name: "Vaso pingüino",
    code: "5008/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 170,
    img: "/productos/vaso-pinguino.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-cuenco-grill",
    name: "Vaso cuenco grill",
    code: "5009/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 386.4,
    img: "/productos/vaso-cuenco-grill.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-pinta",
    name: "Vaso pinta 400 ml",
    code: "5010/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 436.8,
    img: "/productos/vaso-pinta.jpg",
    tags: ["vasos"],
  },
  {
    slug: "taza-vintage",
    name: "Taza vintage",
    code: "5011/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 481.6,
    img: "/productos/taza-vintage.jpg",
    tags: ["vasos"],
  },
  {
    slug: "taza-love",
    name: "Taza love",
    code: "5012/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 481.6,
    img: "/productos/taza-love.jpg",
    tags: ["vasos"],
  },
  {
    slug: "taza-trebol",
    name: "Taza trebol",
    code: "5013/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 453.6,
    img: "/productos/taza-trebol.jpg",
    tags: ["vasos"],
  },
  {
    slug: "jarro-mug-con-tapa",
    name: "Jarro mug con tapa",
    code: "5014/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 560,
    img: "/productos/jarro-mug-con-tapa.jpg",
    tags: ["vasos"],
  },
  {
    slug: "jarro-capuchino",
    name: "Jarro capuchino",
    code: "5014/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 481.6,
    img: "/productos/jarro-capuchino.jpg",
    tags: ["vasos"],
  },
  {
    slug: "vaso-mug",
    name: "Vaso mug",
    code: "5015/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 260.4,
    img: "/productos/vaso-mug.jpg",
    tags: ["vasos"],
  },
  {
    slug: "set-x4-vaso-mug",
    name: "Set x4 vaso mug",
    code: "5015/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1041.6,
    img: "/productos/set-x4-vaso-mug.jpg",
    tags: ["vasos"],
  },
  {
    slug: "jarro",
    name: "Jarro 600 ml",
    code: "5016/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 778.4,
    img: "/productos/jarro.jpg",
    tags: ["vasos"],
  },
  {
    slug: "set-escolar-triple-simple",
    name: "Set escolar triple simple",
    code: "5017/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1176,
    img: "/productos/set-escolar-triple-simple.jpg",
    tags: ["vasos"],
  },
  {
    slug: "set-escolar-triple-formas",
    name: "Set escolar triple formas",
    code: "5017/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1176,
    img: "/productos/set-escolar-triple-formas.jpg",
    tags: ["vasos"],
  },

  {
    slug: "colador-giratorio",
    name: "Colador giratorio",
    code: "9001/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1895.6,
    img: "/productos/colador-giratorio.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "jarra-1.5-lts-con-tapa",
    name: "Jarra 1,5 lts con tapa",
    code: "9002/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1327.2,
    img: "/productos/jarra-1.5-lts-con-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "jarra-1.5-lts-sin-tapa",
    name: "Jarra 1,5 lts sin tapa",
    code: "9002/01",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1044.4,
    img: "/productos/jarra-1.5-lts-sin-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "set-jarra-1.7-lts-4-vasos",
    name: "Set jarra 1,7 lts + 4 vasos",
    code: "9002/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1904,
    img: "/productos/set-jarra-1.7-lts-4-vasos.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "organizador-para-heladera",
    name: "Organizador para heladera",
    code: "9003/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1820,
    img: "/productos/organizador-para-heladera.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "jarra-pinguino-con-tapa",
    name: "Jarra pingüino con tapa",
    code: "9004/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1128.4,
    img: "/productos/jarra-pinguino-con-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "jarra-pinguino-sin-tapa",
    name: "Jarra pingüino sin tapa",
    code: "9004/01",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1038.8,
    img: "/productos/jarra-pinguino-sin-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "escurridor-ovalado",
    name: "Escurridor ovalado",
    code: "9005/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 700,
    img: "/productos/escurridor-ovalado.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "escurridor-para-bacha",
    name: "Escurridor para bacha",
    code: "9006/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1988,
    img: "/productos/escurridor-para-bacha.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "big-cupcake",
    name: "Big cupcake",
    code: "9007/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 478.8,
    img: "/productos/big-cupcake.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "bowl-postre-sweet",
    name: "Bowl postre sweet",
    code: "9008/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 327.6,
    img: "/productos/bowl-postre-sweet.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "bowl-snack",
    name: "Bowl snack",
    code: "9009/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 350,
    img: "/productos/bowl-snack.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "bowl-ovalado",
    name: "Bowl ovalado",
    code: "9010/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 803.6,
    img: "/productos/bowl-ovalado.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "cazuela",
    name: "Cazuela",
    code: "9011/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 560,
    img: "/productos/cazuela.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "cubetera-14",
    name: "Cubetera 14",
    code: "9012/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 756,
    img: "/productos/cubetera-14.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "cubetera-24",
    name: "Cubetera 24",
    code: "9013/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 756,
    img: "/productos/cubetera-24.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "cubetera-44",
    name: "Cubetera 44",
    code: "9014/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 756,
    img: "/productos/cubetera-44.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "set-cubetera-14-con-tapa",
    name: "Set cubetera 14 con tapa",
    code: "9012/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2380,
    img: "/productos/set-cubetera-14-con-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "set-cubetera-24-con-tapa",
    name: "Set cubetera 24 con tapa",
    code: "9013/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2380,
    img: "/productos/set-cubetera-24-con-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "set-cubetera-44-con-tapa",
    name: "Set cubetera 44 con tapa",
    code: "9014/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2380,
    img: "/productos/set-cubetera-44-con-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "dispenser",
    name: "Dispenser",
    code: "9015/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 3427.2,
    img: "/productos/dispenser.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "dispenser-con-4-vasos",
    name: "Dispenser con 4 vasos",
    code: "9015/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 4468.8,
    img: "/productos/dispenser-con-4-vasos.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "cesto-de-puerta",
    name: "Cesto de puerta",
    code: "9016/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1478.4,
    img: "/productos/cesto-de-puerta.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "plato-postre",
    name: "Plato postre",
    code: "9017/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 375.2,
    img: "/productos/plato-postre.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "plato-infantil-iml",
    name: "Plato infantil IML",
    code: "9017/114",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 582.4,
    img: "/productos/plato-infantil-iml.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "jarra-0.76-lts",
    name: "Jarra 0,76 lts",
    code: "9018/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 803.6,
    img: "/productos/jarra-0.76-lts.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "jarra-americana-2.25-lts-con-tapa",
    name: "Jarra americana 2,25 lts con tapa",
    code: "9019/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1453.2,
    img: "/productos/jarra-americana-2.25-lts-con-tapa.jpg",
    tags: ["artículos de cocina"],
  },
  {
    slug: "set-jarra-americana-2.25-lts-3-vasos-mug",
    name: "Set jarra americana 2,25 lts + 3 vasos mug",
    code: "9019/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2234.4,
    img: "/productos/set-jarra-americana-2.25-lts-3-vasos-mug.jpg",
    tags: ["artículos de cocina"],
  },

  {
    slug: "balde-10-lts-negro",
    name: "Balde 10 lts negro",
    code: "8001/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1460,
    img: "/productos/balde-10-lts-negro.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "balde-10-lts-eco-color",
    name: "Balde 10 lts eco color",
    code: "8001/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 1607.2,
    img: "/productos/balde-10-lts-eco-color.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "jabonera-ballena",
    name: "Jabonera ballena",
    code: "8002/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 456.4,
    img: "/productos/jabonera-ballena.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "jabonera-simple",
    name: "Jabonera simple",
    code: "8003/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 310.8,
    img: "/productos/jabonera-simple.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "fuenton-oso",
    name: "Fuentón oso",
    code: "8004/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 2079,
    img: "/productos/fuenton-oso.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "palita-basura-negro",
    name: "Palita basura negro",
    code: "8005/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 518,
    img: "/productos/palita-basura-negro.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "palita-basura-color",
    name: "Palita basura color",
    code: "8005/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 688.8,
    img: "/productos/palita-basura-color.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "percha-economica-negro",
    name: "Percha económica negro * 4",
    code: "8006/00",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 582.4,
    img: "/productos/percha-economica-negro.jpg",
    tags: ["artículos de limpieza"],
  },
  {
    slug: "percha-economica-color",
    name: "Percha económica color * 4",
    code: "8006/99",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit dui, cursus ut auctor a, posuere.",
      "Fusce egestas neque quam. Cras auctor risus vitae aliquam auctor. Quisque eget mi non diam tincidunt semper. Integer ornare tortor et mi scelerisque, sit.",
    ],
    price: 691.6,
    img: "/productos/percha-economica-color.jpg",
    tags: ["artículos de limpieza"],
  },
];

export default products;
