import { Product } from "@/lib/products";

const products: Product[] = [
  {
    slug: "bandeja",
    name: "Bandeja",
    description: [""],
    img: "",
    tags: ["tablas", "platos"],
  },
  {
    slug: "botellas-copetineras",
    name: "Botellas copetineras",
    description: [""],
    img: "",
    tags: ["copetineras"],
  },
  {
    slug: "brochetera-con-tabla",
    name: "Brochetera con tabla",
    description: [""],
    img: "",
    tags: ["tablas", "parrilla"],
  },
  {
    slug: "caja-de-cinco-platos",
    name: "Caja de cinco platos",
    description: [""],
    img: "",
    tags: ["platos", "sets armados"],
  },
  {
    slug: "combo-de-pizza",
    name: "Combo de pizza",
    description: [""],
    img: "",
    tags: ["sets armados", "pizza"],
  },
  {
    slug: "combo-plancheta",
    name: "Combo plancheta",
    description: [""],
    img: "",
    tags: ["sets armados", "planchetas"],
  },
  {
    slug: "copetinera-bifaz",
    name: "Copetinera bifaz",
    description: [""],
    img: "",
    tags: ["copetineras"],
  },
  {
    slug: "copetinera-circular",
    name: "Copetinera circular",
    description: [""],
    img: "",
    tags: ["copetineras"],
  },
  {
    slug: "cucharas-y-espatulas",
    name: "Cucharas y espátulas",
    description: [""],
    img: "",
    tags: ["utensillos"],
  },
  {
    slug: "cuencos-y-cazuelas",
    name: "Cuencos y cazuelas",
    description: [""],
    img: "",
    tags: ["utensillos"],
  },
  {
    slug: "espatula-de-acero-inoxidable",
    name: "Espátula de acero inoxidable",
    description: [""],
    img: "",
    tags: ["utensillos"],
  },
  {
    slug: "espatula-pizzera-de-acero-inoxidable",
    name: "Espátula pizzera de acero inoxidable",
    description: [""],
    img: "",
    tags: ["utensillos", "pizza"],
  },
  {
    slug: "grabado-de-marca",
    name: "Grabado de marca",
    description: [""],
    img: "",
    tags: ["productos personalizados"],
  },
  {
    slug: "jenga-personalizado",
    name: "Jenga personalizado",
    description: [""],
    img: "",
    tags: ["juegos", "productos personalizados"],
  },
  {
    slug: "mate-personalizado",
    name: "Mate personalizado",
    description: [""],
    img: "",
    tags: ["productos personalizados"],
  },
  {
    slug: "pala-y-atizador-de-acero-inoxidable",
    name: "Pala y atizador de acero inoxidable",
    description: [""],
    img: "",
    tags: ["parrilla", "utensillos"],
  },
  {
    slug: "pintas-de-vidrio-estampadas",
    name: "Pintas de vidrio estampadas",
    description: [""],
    img: "",
    tags: ["vasos"],
  },
  {
    slug: "plancheta-de-dos-hornallas",
    name: "Plancheta de dos hornallas",
    description: [""],
    img: "",
    tags: ["planchetas"],
  },
  {
    slug: "plancheta-estampada-personalizada",
    name: "Plancheta estampada personalizada",
    description: [""],
    img: "",
    tags: ["planchetas", "productos personalizados"],
  },
  {
    slug: "plato-circular",
    name: "Plato circular",
    description: [""],
    img: "",
    tags: ["platos"],
  },
  {
    slug: "plato-cuadrado",
    name: "Plato cuadrado",
    description: [""],
    img: "",
    tags: ["platos"],
  },
  {
    slug: "plato-de-campo",
    name: "Plato de campo",
    description: [""],
    img: "",
    tags: ["platos"],
  },
  {
    slug: "plato-ranurado",
    name: "Plato ranurado",
    description: [""],
    img: "",
    tags: ["platos"],
  },
  {
    slug: "plato-circular-de-algarrobo",
    name: "Plato circular de algarrobo",
    description: [""],
    img: "",
    tags: ["platos"],
  },
  {
    slug: "plato-simple",
    name: "Plato simple",
    description: [""],
    img: "",
    tags: ["platos"],
  },
  {
    slug: "plato-rectangular",
    name: "Plato rectangular",
    description: [""],
    img: "",
    tags: ["platos"],
  },
  {
    slug: "porta-notebook-bandeja",
    name: "Porta notebook bandeja",
    description: [""],
    img: "",
    tags: ["porta notebook"],
  },
  {
    slug: "porta-notebook-cruz",
    name: "Porta notebook cruz",
    description: [""],
    img: "",
    tags: ["porta notebook"],
  },
  {
    slug: "reloj",
    name: "Reloj",
    description: [""],
    img: "",
    tags: ["reloj"],
  },
  {
    slug: "salaminera",
    name: "Salaminera",
    description: [""],
    img: "",
    tags: ["tablas"],
  },
  {
    slug: "set-de-parrilla",
    name: "Set de parrilla",
    description: [""],
    img: "",
    tags: ["sets armados", "parrilla"],
  },
  {
    slug: "set-para-asado",
    name: "Set para asado",
    description: [""],
    img: "",
    tags: ["sets armados", "parrilla"],
  },
  {
    slug: "set-para-pizza",
    name: "Set para pizza",
    description: [""],
    img: "",
    tags: ["sets armados", "pizza"],
  },
  {
    slug: "tabla-con-herradura",
    name: "Tabla con herradura",
    description: [""],
    img: "",
    tags: ["tablas"],
  },
  {
    slug: "tabla-con-placa-de-acero-inoxidable",
    name: "Tabla con placa de acero inoxidable",
    description: [""],
    img: "",
    tags: ["tablas"],
  },
  {
    slug: "tabla-con-herradura-y-estampado",
    name: "Tabla con herradura y estampado",
    description: [""],
    img: "",
    tags: ["tablas"],
  },
  {
    slug: "tabla-redonda-con-mango",
    name: "Tabla redonda con mango",
    description: [""],
    img: "",
    tags: ["tablas", "pizza"],
  },
];

export default products;
